function Rot = EulToRotZYX(phi, theta, psi)
% Written by Justin Thomas
% May 2012

% This function returns a rotation matrix based on the Euler angles
% provided.  It uses the ZYX convention.

% We use the ZYX rotation convention with angles psi, theta, phi,
% representing yaw, pitch, and roll, respectively.
% Rx = [1 0 0; 0 cos(phi) -sin(phi); 0 sin(phi) cos(phi)];
% Ry = [cos(theta) 0 sin(theta); 0 1 0; -sin(theta) 0 cos(theta)];
% Rz = [cos(psi) -sin(psi) 0; sin(psi) cos(psi) 0; 0 0 1];
% Rot = Rz*Ry*Rx;

Rot = [...
    cos(psi)*cos(theta),...
    cos(psi)*sin(phi)*sin(theta) - cos(phi)*sin(psi),...
    sin(phi)*sin(psi) + cos(phi)*cos(psi)*sin(theta); ...
    cos(theta)*sin(psi),...
    cos(phi)*cos(psi) + sin(phi)*sin(psi)*sin(theta),...
    cos(phi)*sin(psi)*sin(theta) - cos(psi)*sin(phi);...
    -sin(theta),...
    cos(theta)*sin(phi),...
    cos(phi)*cos(theta)];

end